@MarketOps.Viewer.Backend_HostAddress = http://localhost:5062

GET {{MarketOps.Viewer.Backend_HostAddress}}/api/stocks
Accept: application/json

###
GET {{MarketOps.Viewer.Backend_HostAddress}}/api/stockdata/125?timeframe=monthly&startDate=2020-01-01&endDate=2026-01-01
Accept: application/json

###
